## Intoduction to numpy, pandas, and matplotlib

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np, pd, plt

(<module 'numpy' from '/Users/mattkrepp/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>,
 <module 'pandas' from '/Users/mattkrepp/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py'>,
 <module 'matplotlib.pyplot' from '/Users/mattkrepp/opt/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py'>)

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


## numpy Datatypes
### float32 and float64

In [13]:
x = np.float32(2 ** 127)
x, type(x)

(1.7014118e+38, numpy.float32)

In [14]:
x = np.float32(2 ** 128)
x, type(x)

(inf, numpy.float32)

In [15]:
x = np.float64(2 ** 1023)
x, type(x)

(8.98846567431158e+307, numpy.float64)

In [16]:
x = np.float64(2 ** 1024)
x, type(x)

OverflowError: int too large to convert to float

## Arrays have a fixed datatype

In [18]:
list = [1.,2.,3.,4.,5.]
array = np.array(list)
array, type(array), array.dtype

(array([1., 2., 3., 4., 5.]), numpy.ndarray, dtype('float64'))

In [24]:
# np.arange creates array similar to how one would use a for loop // generator to create a list
start = 0
end = 100
interval = 10
range_array = np.arange(start,end + 1, interval)
range_array

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [25]:
range_list = [i for i in range(start, end + 1, interval)]
range_list

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

## Two Dimensional Lists and Arrays

### Create Two Dimensional List

In [26]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### Transform that Two Dimensional List into Two Dimensional Array

In [29]:
two_dim_array = np.array(list_of_lists)
two_dim_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
two_dim_array[0]

array([1, 2, 3])

In [41]:
two_dim_array[0][0]

1

### Call the 1st Element of the 0th row

In [40]:
two_dim_array[0][1]

2

### Use for loop to call the first index in the two_dim_array as i, calling two_dim_array will yield ith row

In [34]:
for i in range(len(two_dim_array)):
    print(i)
    print(two_dim_array[i])

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]


### Passing the row to a second for loop will cycle through the second row index as j. Calling row j will yield the jth value from the row

In [38]:
print("i j:")
for i in range(len(two_dim_array)):
    row = two_dim_array[i]
    for j in range(len(two_dim_array[i])):
        print(i,j)
        print("val:", row[j])

i j:
0 0
val: 1
0 1
val: 2
0 2
val: 3
1 0
val: 4
1 1
val: 5
1 2
val: 6
2 0
val: 7
2 1
val: 8
2 2
val: 9


In [39]:
for row in two_dim_array:
    print(row)
    for val in row:
        print(val)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


## np.zeros(), np.ones(), np.empty(), np.zeros_like(), np.ones_like(), np.empty_like()

In [43]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.empty((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
l = list_of_lists
np.zeros_like(l)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
l = list_of_lists
np.ones_like(l)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
np.empty_like(l)

array([[                  0,                  15,                   0],
       [                  0, 4613349223037927424, 3619035046246376291],
       [3473450901998756397, 3270005191049295417, 3472333811116684085]])

## Log Values

In [51]:
np.log(1)

0.0

In [52]:
np.log(np.e)

1.0

In [53]:
np.log(two_dim_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [54]:
pi = np.pi
e = np.e
lne = np.log(e)
infinity = np.inf
null_val = np.nan
pi, e, lne, infinity, null_val

(3.141592653589793, 2.718281828459045, 1.0, inf, nan)